force-app/main/default/objects/MultPEFImportSettings__mdt/MultPEFImportSettings__mdt.object-meta.xml
<CustomObject>
    <label>MultPEFImportSettings</label>
    <pluralLabel>MultPEFImportSettings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MultPEFImportSettings__mdt/fields/fieldDelimiter__c.field-meta.xml
<CustomField>
    <fullName>fieldDelimiter__c</fullName>
    <label>fieldDelimiter</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MultPEFImportSettings__mdt/fields/ImportIdPos__c.field-meta.xml
<CustomField>
    <fullName>ImportIdPos__c</fullName>
    <label>ImportIdPos</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MultPEFImportSettings__mdt/fields/lineDelimiter__c.field-meta.xml
<CustomField>
    <fullName>lineDelimiter__c</fullName>
    <label>lineDelimiter</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MultPEFImportSettings__mdt/fields/ReportNumberPos__c.field-meta.xml
<CustomField>
    <fullName>ReportNumberPos__c</fullName>
    <label>ReportNumberPos</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MultPEFImportSettings__mdt/fields/RTName__c.field-meta.xml
<CustomField>
    <fullName>RTName__c</fullName>
    <label>RTName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewCtrlMultPEFImport.cls
public class NewCtrlMultPEFImport {
    public Blob csvFileBody{get;set;}
    public String csvAsString{get;set;}
    public String[] csvFileLines{get;set;}
    private String fieldDelimiter;
    public NewCtrlMultPEFImport(){
        csvFileLines = New String[]{};
            MultPEFImportSettings__mdt MySettings = [SELECT fieldDelimiter__c, ImportIdPos__c, lineDelimiter__c, ReportNumberPos__c, RTName__c
	    											FROM MultPEFImportSettings__mdt
	    											WHERE MasterLabel = 'DefaultSettings'];
        fieldDelimiter = MySettings.fieldDelimiter__c;
        
    }
    public void importCSVFile(){
        csvAsString = csvFileBody.toString();
        csvFileLines = csvAsString.split('\n'); 
        List<String> nextcsvRecordData= new List<String>();
        String nextRecord; 
        for(Integer i=0;i<csvFileLines.size();i++){
            try{
                String currentRecord = csvFileLines[i];
            	List<String> csvRecordData = currentRecord.split(',');
            }
            catch(exception e){
                system.debug('1234'+e);
            }
            
            
    	}

	}
}