force-app/main/default/objects/Kit_Assessment__c/Kit_Assessment__c.object-meta.xml
<CustomObject>
    <label>Kit Assessment</label>
    <nameField>
        <displayFormat>k-{0000}</displayFormat>
        <label>Kit Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kit Assessment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Kit_Assessment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Kit Assessment</relationshipLabel>
    <relationshipName>Kit_Assessment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Assessed_By__c.field-meta.xml
<CustomField>
    <fullName>Assessed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Kit_Assessment1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Assessed_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessed_Date__c</fullName>
    <label>Assessed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Has_Kit__c.field-meta.xml
<CustomField>
    <fullName>Has_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/KitOrder__c.field-meta.xml
<CustomField>
    <fullName>KitOrder__c</fullName>
    <formula>Value(Text( Product__r.kit_Order__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KitOrder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Needs_Kit__c.field-meta.xml
<CustomField>
    <fullName>Needs_Kit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Kit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Kit Assessment</relationshipLabel>
    <relationshipName>Kit_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>JnJ Kits</fullName>
            </value>
            <value>
                <fullName>Competitor Kits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Kit_Assessment__c/fields/Vendor_From_Product__c.field-meta.xml
<CustomField>
    <fullName>Vendor_From_Product__c</fullName>
    <formula>Text(Product__r.Vendor__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor From Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/cls_jjvc_KitAssessments.cls
public Class cls_jjvc_KitAssessments{
public String kitsType{get;set;}
public string theValue { get; set; }
public Id userid{get;set;}
public Account acc{get;set;}
public List<Kit_Assessment__c> kitsAssesmentList { get; set; } 
    public cls_jjvc_KitAssessments(ApexPages.StandardController controller)
    {
    system.debug('theValue' + theValue);
    kitsType='JJVC';
    acc=(Account) controller.getRecord();
    userid=userInfo.getUserId();
    }
    
    public void getAssessmentKits(){
        if(String.isnotBlank(kitsType)){
         kitsAssesmentList= [
                    SELECT Id, Name, Account__c, Assessed_By__c, Assessed_By__r.Alias, Assessed_Date__c, Product__r.IsActive, Has_Kit__c, Needs_Kit__c, KitOrder__c, Product__r.name, Type__c, Vendor_From_Product__c, Shipped_Date__c
                    FROM Kit_Assessment__c
                    WHERE Account__c = :acc.Id AND Vendor_From_Product__c = :kitsType AND Product__r.IsActive = true
                    order by KitOrder__c asc
            ];
        }
    }
}