force-app/main/default/objects/Account_Call__c/Account_Call__c.object-meta.xml
<CustomObject>
    <label>Account Call</label>
    <nameField>
        <label>Account Call Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Call__c/fields/Account_Calls__c.field-meta.xml
<CustomField>
    <fullName>Account_Calls__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Account, Business Account</value>
        </filterItems>
        <infoMessage>Only Business Accounts and Academic Accounts are shown in this screen.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Calls</relationshipLabel>
    <relationshipName>Account_Calls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Adhoc_Activities__c.field-meta.xml
<CustomField>
    <fullName>Adhoc_Activities__c</fullName>
    <label>Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dx Replenishment</fullName>
            </value>
            <value>
                <fullName>Rx Replenishment</fullName>
            </value>
            <value>
                <fullName>Staff Training</fullName>
            </value>
            <value>
                <fullName>Staff Training-Annual Supply</fullName>
            </value>
            <value>
                <fullName>Staff Training-Indus Knowledge</fullName>
            </value>
            <value>
                <fullName>Staff Training-Other</fullName>
            </value>
            <value>
                <fullName>Tech Follow-up</fullName>
            </value>
            <value>
                <fullName>Doctor Dinner</fullName>
            </value>
            <value>
                <fullName>Retail Management</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Adhoc_Activities_CN__c.field-meta.xml
<CustomField>
    <fullName>Adhoc_Activities_CN__c</fullName>
    <label>Activities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dx Replenishment</fullName>
            </value>
            <value>
                <fullName>Rx Replenishment</fullName>
            </value>
            <value>
                <fullName>Staff Training</fullName>
            </value>
            <value>
                <fullName>Staff Training-Annual Supply</fullName>
            </value>
            <value>
                <fullName>Staff Training-Indus Knowledge</fullName>
            </value>
            <value>
                <fullName>Tech Follow-up</fullName>
            </value>
            <value>
                <fullName>Staff Training-Other</fullName>
            </value>
            <value>
                <fullName>Doctor Dinner</fullName>
            </value>
            <value>
                <fullName>Retail Management</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presentation Only</fullName>
            </value>
            <value>
                <fullName>Office Process</fullName>
            </value>
            <value>
                <fullName>Presentation &amp; Office Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Next_Schedule_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Schedule_Call_Date__c</fullName>
    <label>Next Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Next_Scheduled_Account_Call__c.field-meta.xml
<CustomField>
    <fullName>Next_Scheduled_Account_Call__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Scheduled Account Call</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Calls__c</field>
            <operation>equals</operation>
            <valueField>Account_Call__c.Account_Calls__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account_Call__c</referenceTo>
    <relationshipLabel>Account Calls</relationshipLabel>
    <relationshipName>Account_Calls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/SAP_EXTRACT_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SAP_EXTRACT_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP EXTRACT FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>open</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <label>Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed Inbound</fullName>
            </value>
            <value>
                <fullName>Left Voicemail</fullName>
            </value>
            <value>
                <fullName>Completed Outbound</fullName>
            </value>
            <value>
                <fullName>Talked to Receptionist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCallViewExtention.cls
public class AccountCallViewExtention {
public Account_Call__C accCall;
public boolean showUnlockButton {get;set;}
public boolean showEditButton {get;set;}
public boolean showCallAttendees{get;set;}
public Boolean show_SAP_Flag_ToAdmin{get;set;}
public String accountAddress{get;set;}
public Id AccountCallId;
public list<String> selectedAdhocActivitiesList{get;set;}
    public AccountCallViewExtention (ApexPages.StandardController controller)
    {
    AccountCallId=ApexPages.currentPage().getParameters().get('Id');
    Try
     {
     accCall=[select id, Status__c, Sub_Status__c, createdById, SAP_EXTRACT_FLAG__c, Adhoc_Activities_CN__c, Adhoc_Activities__c, Account_Calls__c, Account_Calls__r.Name, Start_Date__c, previous_status__c, Call_Type__c, Next_Schedule_Call_Date__c,
                            Account_Calls__r.ShippingAddress, Account_Calls__r.shippingStreet, Account_Calls__r.ShippingCity, Account_Calls__r.ShippingState, Account_Calls__r.ShippingPostalCode, Account_Calls__r.ShippingCountry
                    from Account_Call__c
                    where id = :AccountCallId];
     if(!String.isBlank(accCall.Adhoc_Activities__c)){
             selectedAdhocActivitiesList=accCall.Adhoc_Activities__c.split(';');  
          }            
 
    }
     catch (System.QueryException e) {      
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Record is deleted');
            ApexPages.addMessage(myMsg); 
      }
    }
    public pageReference submit()
    {
    return null;
    }
   List<String> accountAddressField=new List<String>(); 
}