force-app/main/default/objects/Account_Call__c/Account_Call__c.object-meta.xml
<CustomObject>
    <label>Account Call</label>
    <nameField>
        <label>Account Call Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Call__c/fields/Account_Calls__c.field-meta.xml
<CustomField>
    <fullName>Account_Calls__c</fullName>
    <label>Account</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Academic Account, Business Account</value>
        </filterItems>
        <infoMessage>Only Business Accounts and Academic Accounts are shown in this screen.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Calls</relationshipLabel>
    <relationshipName>Account_Calls</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Duration_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_Minutes__c</fullName>
    <label>Duration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>105</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCallController.cls
public with sharing class AccountCallController {
public final id usId{get; set;}
public Account_call__c AccountCall {get;set;}
public String AccountNumber{ get;set; }
public final string pageUrl{get;set;} 
public string AccountName{get;set;}
public ID accId;
    public AccountCallController(ApexPages.standardController controller)
    {
    Id usId=userInfo.getUserid();
    AccountCall = new Account_call__c();
    system.debug('login user id is:'+usId); 
    pageUrl=apexPages.currentPage().getURL();
    system.debug('current page url is :'+pageUrl);
    system.debug('page url is:'+pageUrl);
    final Integer result = pageUrl.indexOf('_lkid=');
    system.debug('result is :'+result);
    if (result!=-1) {
                AccId = pageUrl.substring(result + 6, result + 6 + 15);
                system.debug('result-->' + result);
                system.debug('id-->' + AccId);
                AccountCall.Account_Calls__c = accId; 
                AccountCall.Duration_Minutes__c='30';
                system.debug('account_calls__c is :'+accountCall.account_calls__c);  
                populateActivities();      
                    }
     }
     public void populateActivities()
     {
     Account acc;
     system.debug('with in method');
      AccountName=[select name from Account where Id =: AccountCall.Account_Calls__c][0].Name;
     system.debug('After method'+AccountName);
     acc=[select accountNumber from account where Id =: AccountCall.Account_Calls__c];
     system.debug('account number is :'+acc.AccountNumber);
     AccountNumber=acc.AccountNumber;
     }
}