force-app/main/default/objects/Account_Call__c/Account_Call__c.object-meta.xml
<CustomObject>
    <label>Account Call</label>
    <nameField>
        <label>Account Call Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Calls</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Call__c/fields/SAP_EXTRACT_FLAG__c.field-meta.xml
<CustomField>
    <fullName>SAP_EXTRACT_FLAG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SAP EXTRACT FLAG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Call__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>open</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountCallHandler.cls
Public class AccountCallHandler
{
    public static void restrictAccCallBeforeUpdateDelete(list<Account_call__c> laccntcall,boolean isUpdate,boolean isDelete)
    {
        Id adminProfileId = [select id,name from profile where name=:'System Administrator'].id;
        id modifieduserId=userInfo.getProfileId();
        for(Account_call__c acccall:laccntCall)
            {
                if((isUpdate) && adminProfileId !=modifiedUserId && (acccall.status__c=='Submitted' || acccall.status__c=='Appointed' || (acccall.SAP_EXTRACT_FLAG__c)))
                {
                acccall.addError('You are nor allowed to modify the account call');
                }
                if((isDelete) && adminProfileId !=modifiedUserId && (acccall.status__c=='Submitted' || acccall.status__c=='Appointed'|| (acccall.SAP_EXTRACT_FLAG__c)))
                {
                acccall.addError('You are nor allowed to Delete the account call');
                }
            }        
    } 
}