force-app/main/default/objects/Phone__c/Phone__c.object-meta.xml
<CustomObject>
    <label>Phone</label>
    <nameField>
        <displayFormat>Ph-{000000}</displayFormat>
        <label>Phone Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/PhoneHelper.cls
Public class PhoneHelper{
// For validating delete user
public void validateDeleteUser(List<phone__c> phoneList){
  Id  currentUserProfileId;
  for(phone__c p:phoneList){
  if(currentUserProfileId==system.label.AdminId && (p.source__c=='SLX' || p.source__c=='Manually Entered')){
     }
      else{
       p.addError('You do not have right to delete the records');
      }
  }
 }
public void validatePhoneformat(list<Phone__c> phonelist){
 String strPhone;
 String specialChars = '&|^|@|*|#|%|!|$|(|)|-'; 
 for (Phone__c objTemp:phoneList){
    if(objTemp.number__c!=null){
       strPhone=objTemp.number__c;
        for(string s : specialChars .split('|')){
                    strPhone = strphone.remove(s).replaceAll( '\\s+', '');
                }
       if(strPhone.length()>10 && strPhone.isalphanumeric())
       objTemp.number__c=objTemp.number__c;
       else
        objTemp.number__c=strPhone;
     }
   }
 }
}